version: '3.8'

services:
  rexploit:
    image: kalilinux/kali-rolling:latest
    container_name: rexploit-container
    volumes:
      - ./:/opt/rexploit
      - rexploit-data:/root/.rexploit
    ports:
      - "4444:4444"  # Default RexPloit listener
      - "8080:8080"  # Web interface
      - "8888:8888"  # C2 framework
    environment:
      - DISPLAY=${DISPLAY}
      - TERM=xterm-256color
    command: >
      bash -c "apt-get update && 
               apt-get install -y python3 python3-pip git curl wget nmap &&
               cd /opt/rexploit &&
               pip3 install -r requirements.txt &&
               mkdir -p /root/.rexploit/c2_frameworks &&
               echo 'alias rexploit=\"cd /opt/rexploit && python3 rexploit.py\"' >> /root/.bashrc &&
               echo 'alias rexploit-cli=\"cd /opt/rexploit && python3 rexploit.py --cli\"' >> /root/.bashrc &&
               /bin/bash"
    restart: unless-stopped
    tty: true
    stdin_open: true
    cap_add:
      - NET_ADMIN  # Allow network operations

volumes:
  rexploit-data: